### ISSUE TITLE
想问个问题

### ISSUE THREAD

**Issue by lovefisher** [fanqingxuan/gin-skeleton#1]
在controller里写的log.Info方法 要求的是content.Context 为什么传的是gin的Context ide一直显示error

**Comment by lovefisher** [comment]
另外repository的find方法好像不支持where 需要自己补上参数 比如user的login

**Comment by fanqingxuan** [comment]
不好意思刚看到，后续我改下，因为gin.context实现了context.context所有方法，所以实现了继承，这在语法上没问题










在 2021-01-30 11:20:00，"lovefisher" <notifications@github.com> 写道：

在controller里写的log.Info方法 要求的是content.Context 为什么传的是gin的Context ide一直显示error

**Comment by fanqingxuan** [comment]
> 在controller里写的log.Info方法 要求的是content.Context 为什么传的是gin的Context ide一直显示error

您好，gin.Context实现了context.Context接口的所有方法，所以编译不会报错，不知道您用的什么编辑器，我用的vs code ide没有报错呢

**Comment by fanqingxuan** [comment]
> 另外repository的find方法好像不支持where 需要自己补上参数 比如user的login

您好，我只是提供了一个基本的目录结构，dao里面的方法，只是我写的一个demo，你可以根据自己的需要修改成自己实际需要的

**Comment by fanqingxuan** [comment]
如上回复

**Comment by fanqingxuan** [comment]
从网易163邮箱发来的超大附件推荐客户端极速下载
scms.zip (46.2M, 2025年10月12日 11:08 到期)
下载
